In [67]:
import numpy as np

tab = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

tabRand = np.random.randint(100, size=(6,4))

tabRand2 = np.random.randint(100, size=(4,4))

tabConcat = np.concatenate([tabRand, tabRand2])

# print( tabConcat )

dataCSV = np.genfromtxt("stock.csv", delimiter=",", dtype=int)

## fichier Prix total en dollar 0,86 / Nb de Velo / Nb de piece / Ref Marque

#1 Convertir le prix en euro sachant que le dollar est a 0.86 euro

dataCSV[:, 0] = dataCSV[:, 0] * 0.86

print ( dataCSV )



#2 Combien de Marque ont des stock de plus de 2000 vélo

sup = 2000
marque_len = len( dataCSV[ dataCSV[:, 1] > sup ] )
print( "Number of brands with more than %d velo: %d" % (sup, marque_len) )



#3 Calculer la somme total de pieces en stock

print(dataCSV[0::2, 2])
total_pieces = np.sum(dataCSV[0::2, 2])
print( "Total pieces: %d" % total_pieces )



#4 Quelle est le stock de vélo de la marque qui a la plus grande trésorie

highest_thunes = np.max( dataCSV[:, 0] )
marque_highest_thunes = dataCSV[dataCSV[:, 0] == highest_thunes][0, 1]

print( marque_highest_thunes )

[[182320   4148  25264      1]
 [197800   2501  11891      2]
 [291540   4374  25351      3]
 [248540   2398  22215      4]
 [137600   2536   9234      5]
 [ 73100   2368  13329      6]
 [ 73100   1264   8407      7]
 [124700   1572  12588      8]
 [141040   2375  16204      9]
 [106210   1161   9626     10]
 [154800   1542   8755     11]
 [137170   1464  14636     12]
 [134160   2240  21780     13]
 [125990   1269  11250     14]
 [ 87290    924   7361     15]
 [ 94428    768  10497     16]
 [156520   1320  15768     17]
 [ 94600   1845  12153     18]
 [107500   1274  13634     19]
 [ 68800   1905  10890     20]]
Number of brands with more than 2000 velo: 8
[25264 25351  9234  8407 16204  8755 21780  7361 15768 13634]
Total pieces: 151758
4374
